baron:
  cluster_number: 8
  n_gfm: 4
  gfm_extension_cutoff: 0.08
  full_alpha: 0.001
  full_beta: 1

darmanis:
  cluster_number: 9
  n_gfm: 4
  gfm_extension_cutoff: 0.31
  full_alpha: 0.01
  full_beta: 1

lake:
  cluster_number: 6
  n_gfm: 5
  gfm_extension_cutoff: 0.12
  full_alpha: 1
  full_beta: 1

li:
  cluster_number: 9
  n_gfm: 3
  gfm_extension_cutoff: 0.33
  full_alpha: 1
  full_beta: 1

muraro:
  cluster_number: 7
  n_gfm: 5
  gfm_extension_cutoff: 0.13
  full_alpha: 0.001
  full_beta: 1
